name: Trigger auto deployment for swiftfiddle-runner-functions-503

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/swiftfiddle-runner-functions-503-AutoDeployTrigger-51335015-39e9-4358-b6cd-0c3b14e1c84c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS503_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: swiftfiddle.azurecr.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS503_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS503_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-503
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle.azurecr.io/swiftfiddle-runner-functions-503:${{ github.sha }}
          

     

